[supabase]
url = "https://qkbzjcsfwvzzrdlvkmtc.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYnpqY3Nmd3Z6enJkbHZrbXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NTQwODEsImV4cCI6MjA4MDQzMDA4MX0.rxpGHyMocUVcne6dWSmE_5d0VkxShPIydu0RHIxLoEw
"

